baseURL = "https://coyote.tech"
title = "Coyote Technologies LLC"
author = "john"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Coyote Technologies Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Coyote Technologies LLC"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Coyote Technologies LLC homepage"
    meta_og_title = "Coyote Technologies LLC"
    meta_og_type = "website"
    meta_og_url = "https://coyote.tech"
    meta_og_image = ""
    meta_og_descripticion = ""
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@john_e_bones"
    meta_twitter_creator = "@john_e_bones"

[menu]

#  [[menu.main]]
#    identifier = "products"
#    name = "Products"
#    url = "/products/"
#    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/coyote-technologies"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 1
