on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: build and deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: build site
        run: npm run build
      - name: copy site files
        run: |
          rsync -vazP --delete ./public/ /var/www/html/
